spring:
  application:
    name: meowpet
  datasource:
    url: jdbc:postgresql://localhost:5432/meowpetdb
    username: postgres
    password: qwpo1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb+srv://longphu753951:fSetC1S8Dn0z59Fz@cluster0.ewijxkf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: meowpetdb
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: longphu
      password: 123456
logging:
  level:
    org.springframework: INFO
    com.meowpet: DEBUG
