spring:
  application:
    name: meowpet
  datasource:
    url: jdbc:postgresql://localhost:5432/meowpetdb
    username: postgres
    password: qwpo1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb+srv://longphu753951:fSetC1S8Dn0z59Fz@cluster0.ewijxkf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: meowpetdb
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: longphu
      password: 123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: tranfu1999@gmail.com
    password: kgwu cthd ccwl zefx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.springframework: INFO
    com.meowpet: DEBUG
jwt:
  expiration: 2592000
  expiration-refresh-token: 5184000
  secretKey: bongvamapladoibanthanbongmautrangconmapmaudenbongdammapvamapkhochuhu
api:
  prefix: /api/v1
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"
